app/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView
from django.urls import re_path
from .views import AboutView, contacts, policy, frequentlyaskedquestions

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('django.contrib.auth.urls')),
    path('authentication/', include('authentication.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', TemplateView.as_view(template_name='authenticate/profile.html'), name='user_profile'),
    path('about/', AboutView, name='about'),
    path('contact/', contacts, name='contacts'),
    path('frequently-asked-questions/', frequentlyaskedquestions, name='frequentlyaskedquestions'),
    path('policy/', policy, name='privacy-policy'),

    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name="account/password_reset.html"),
         name="reset_password"),
    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"),
         name="password_reset_done"),
    path('', include('blog.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from . import views
from django.urls import path

app_name = 'blog'
urlpatterns = [


    # path('', views.HomeView.as_view(), name='home'),
    path('', views.HomeView.as_view(), name='home'),

    path('search/', views.SearchView.as_view(), name='search'),
    # path('<slug:slug>/', views.PostDetailView.as_view(), name='single-post' ),
    
    path('<slug:slug>/', views.PostDetailView.as_view(), name='single-post'),



    #
    path('category/<slug:slug>', views.CategoryView.as_view(), name='post-category'),
    path('tag/<int:id>', views.TagView.as_view(), name='tag'),
    path('member/subscription/', views.SubscriptionView.as_view(), name='member-subscription'),
    path('<int:id>/create-comment/', views.CommentView.as_view(), name='comment'),

    # Author
    path('author/<int:pk>/', views.AuthorProfile.as_view(), name='author-profile'),
    path('author/<int:pk>/edit/', views.AuthorUpdateView.as_view(), name="author-edit"),

    # Images
    path('images', views.ImageList.as_view(), name="image-list"),
    path("images/upload", views.CreateImagePostView.as_view(), name="image-upload"),
    path('images/<int:pk>/', views.ImageDetailView.as_view(),name='image-detail'),
    path('images/<int:pk>/edit/', views.ImageUpdateView.as_view(), name='image-update'),
    path('images/<int:pk>/delete/', views.ImageDeleteView.as_view(),  name='image-delete'),

    # Articles
    path('article/', views.ArticleOne, name='article-one'),

] 

templates/includes/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<link rel="icon" href="{% static 'images/programming/favicon.ico' %}" type="image/x-icon"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
<title>{% block title %} {% endblock %}</title>
<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport'/>
<!-- Google Font -->
<link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700|Source+Sans+Pro:400,600,700" rel="stylesheet">
<!-- Font Awesome Icons -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
<!-- Main CSS -->
<link rel="stylesheet" href="{% static 'blog/assets/css/main.css' %}">

</head>
<body>
{% include 'includes/header.html' %}
{% block body %} {% endblock %}
<!-- start Footer -->
{% include 'includes/footer.html' %}
<!-- End Footer -->

<!--------------------------------------
JAVASCRIPTS
--------------------------------------->
<script src="{% static 'blog/assets/js/vendor/jquery.min.js' %}"></script>
<script src="{% static 'blog/assets/js/vendor/popper.min.js' %}"></script>
<script src="{% static 'blog/assets/js/vendor/bootstrap.min.js' %}"></script>
<script src="{% static 'blog/assets/js/vendor/functions.js' %}"></script>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


</body>
</html>

templates/includes/footer.html
<div class="container mt-5" >
	<footer class="bg-white border-top p-3 text-muted small" style="bottom: 100px;">
	<div class="row align-items-center justify-content-between">
		<div>
            <span class="navbar-brand mr-2"><strong>{{site_name}}</strong></span> Copyright &copy;
			<script>document.write(new Date().getFullYear())</script>
			 . All rights reserved.
		</div>
		| <a href="{% url 'about'%}" class="btn btn-outline-success">About</a> |
		<a href="{% url 'contacts' %}" class="btn btn-outline-success">Contact Us</a> | <a href="{% url 'privacy-policy' %}" class="btn btn-outline-success">Privacy Policy</a>|
	</div>
	</footer>
</div>

templates/includes/header.html
<!--------------------------------------
NAVBAR
--------------------------------------->
<style>
  a {
    color: black !important; /* Remove the text underline */
    text-decoration: none !important;
    border-bottom: none !important; /* Remove the underline border */
    font-size: 18px;
    font-weight: bold;
  }

  a:hover {
    color: red !important;
  }
</style>



<nav class="topnav navbar navbar-expand-lg navbar-light bg-white fixed-top">


    <div class="container">
        <a class="navbar-brand" href="{% url 'blog:home' %}"><strong>{{site_name}}</strong></a>
        <a class="navbar-brand" href="{% url 'blog:home' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-fill"
                 viewBox="0 0 16 16">
                <path fill-rule="evenodd"
                      d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
                <path fill-rule="evenodd"
                      d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
            </svg>
        </a>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarColor02"
                aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbarColor02">
            <ul class="navbar-nav mr-auto d-flex align-items-center">
                {% for cat in topics %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:post-category' cat.slug %}">{{ cat }}</a>
                </li>

                {% endfor %}
                <li class="nav-item">
                    {% if cat_count > 4 %}
                    <a class="nav-link" href="#"><span class="badge badge-secondary"> More Categories </span></a>
                    {% endif %}
                </li>

                <li>
<!--&lt;!&ndash;                    <form class="form-inline form-control-sm" method="GET" action="{% url 'blog:search' %}">&ndash;&gt;-->
<!--&lt;!&ndash;                        <input class="form-control form-control-sm mr-sm-1 input-sm" id="form1" value="{{ search }}"&ndash;&gt;-->
<!--&lt;!&ndash;                               type="search" name='q' placeholder="Search" aria-label="Search" required>&ndash;&gt;-->
<!--                        <button class="btn btn-outline-success btn-sm my-2 my-sm-0" type="submit"><i-->
<!--                                class="fa fa-search"></i></button>-->
                    </form>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto d-flex align-items-center">
                {% if request.user.is_authenticated %}
                <li>
                    <a class="nav-link" href="{% url 'authentication:logout' %}"><i class="fas fa-sign-out-alt"></i></a>
                </li>
                {% else %}
                {% comment %} <li class="nav-item highlight">
                    <a class="nav-link" href="{% url 'authentication:login' %}"> Login Now </a>

                </li> {% endcomment %}
                {% endif %}
                
            </ul>
<a href="https://www.youtube.com/channel/UC85UrvpP4UtMDhnOWVyYwCw?sub_confirmation=1" target="_blank">YouTube Channel</a>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://www.facebook.com/profile.php?id=61552498204633&__tn__=%3C" target="_blank">Facebook</a>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://www.facebook.com/profile.php?id=61552498204633&__tn__=%3C" target="_blank">Whatsapp</a>
               &nbsp;&nbsp;&nbsp;&nbsp; <form action="/search" method="get">
    <input type="text" name="q" placeholder="Search...">
          &nbsp;<button class="btn btn-outline-success btn-sm my-2 my-sm-0" type="submit"><i class="fa fa-search"></i></button>
<!--    <button type="submit">Search</button>-->
  </form>
        </div>
    </div>

</nav>
<!-- End Navbar -->

templates/includes/messages.html
{% if messages %}

<style type="text/css">
    div.messages{
        
    }
    ul.messages{
        list-style-type: none;
    }
</style>

<div class="alert alert-warning alert-dismissible fade show">
    <ul>
        {% for message in messages %}
        <li {% if message.tags %} class="{{message.tags}}" {% endif %}>
            {% if "html_safe" in message.tags %}
                {{message|safe}}
            {% else %}
                {{message}}
            {% endif %}
        </li>
        {% endfor %}
    </ul>
</div>

{% endif %}