app/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView
from django.urls import re_path
from .views import AboutView, contacts, policy, frequentlyaskedquestions

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('django.contrib.auth.urls')),
    path('authentication/', include('authentication.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', TemplateView.as_view(template_name='authenticate/profile.html'), name='user_profile'),
    path('about/', AboutView, name='about'),
    path('contact/', contacts, name='contacts'),
    path('frequently-asked-questions/', frequentlyaskedquestions, name='frequentlyaskedquestions'),
    path('policy/', policy, name='privacy-policy'),

    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name="account/password_reset.html"),
         name="reset_password"),
    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"),
         name="password_reset_done"),
    path('', include('blog.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from . import views
from django.urls import path

app_name = 'blog'
urlpatterns = [


    # path('', views.HomeView.as_view(), name='home'),
    path('', views.HomeView.as_view(), name='home'),

    path('search/', views.SearchView.as_view(), name='search'),
    # path('<slug:slug>/', views.PostDetailView.as_view(), name='single-post' ),
    
    path('<slug:slug>/', views.PostDetailView.as_view(), name='single-post'),



    #
    path('category/<slug:slug>', views.CategoryView.as_view(), name='post-category'),
    path('tag/<int:id>', views.TagView.as_view(), name='tag'),
    path('member/subscription/', views.SubscriptionView.as_view(), name='member-subscription'),
    path('<int:id>/create-comment/', views.CommentView.as_view(), name='comment'),

    # Author
    path('author/<int:pk>/', views.AuthorProfile.as_view(), name='author-profile'),
    path('author/<int:pk>/edit/', views.AuthorUpdateView.as_view(), name="author-edit"),

    # Images
    path('images', views.ImageList.as_view(), name="image-list"),
    path("images/upload", views.CreateImagePostView.as_view(), name="image-upload"),
    path('images/<int:pk>/', views.ImageDetailView.as_view(),name='image-detail'),
    path('images/<int:pk>/edit/', views.ImageUpdateView.as_view(), name='image-update'),
    path('images/<int:pk>/delete/', views.ImageDeleteView.as_view(),  name='image-delete'),

    # Articles
    path('article/', views.ArticleOne, name='article-one'),

] 

blog/forms.py
from django import forms
from .models import Image,Author

class ImageForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = ["name", "image"]

        widgets = {
            'name': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Name', 'label': 'Name'}),

        }

class AuthorForm(forms.ModelForm):

    class Meta:
        model = Author
        fields = ["author_image", "title", "profile"]

        widgets = {
            'title': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Title', 'label': 'Title'}),
            'profile': forms.Textarea(
                attrs={'class': 'form-control', 'placeholder': 'Author Profile', 'rows': 3})

        }

blog/views.py
from django.urls import reverse_lazy
from django.utils.safestring import mark_safe
from django.views import generic
from django.views.generic import CreateView, DetailView, UpdateView, ListView, DeleteView

from .models import Post
from django.core import paginator
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.db.models.fields import EmailField
from django.shortcuts import render, redirect,get_object_or_404
from django.views import View
from .models import Post, Category,Tag, EmailSignUp,Comment,Author, Image
from django.core.paginator import Paginator
from django.db.models import Count, F
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.db.models import Count, Sum
from authentication.models import User
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from analytics.mixins import ObjectViewedMixin
from .forms import ImageForm, AuthorForm


# class HomeView(generic.ListView):
#     # queryset = Post.objects.filter(status=1).order_by('-created_on')
#     model = Post
#     template_name = 'blog/index.html'

#     def get_context_data(self, *, object_list=None, **kwargs):
#         featured_obj = Post.objects.all().filter(status='active', visible=True, featured=True).order_by('categories',
#                                                                                                         '-created_on')[
#                        :5]
#         print(featured_obj)  # Add this line for debugging


    
#         # featured_obj = Post.objects.all().filter(status='active', visible=True, featured=True).order_by('categories', '-created_on')[:5]

#         popular_obj = Post.objects.all().filter(status='active', visible=True, popular=True).order_by('categories',
#                                                                                                         '-created_on')[
#                        :5]
#         post_obj = Post.objects.all().filter(status='active', visible=True).order_by('categories', '-created_on')

#         # As per Templates Views
#         first_post = featured_obj.first() if featured_obj else ''
#         s_post = featured_obj[0] if featured_obj else ''
#         last_post = featured_obj[2:] if featured_obj else ''

#         context =super().get_context_data(**kwargs)
#         context['post'] =post_obj
#         context['f_post'] =featured_obj
#         context['p_post'] =popular_obj
#         context['first'] =first_post
#         context['s_post'] =s_post
#         context['last_post'] =last_post
#         return context
    


class HomeView(generic.ListView):
    def get(self, request, *args, **kwargs):
        featured_obj = Post.objects.all().filter(post_status='active', visible=True, featured=True).order_by('categories','-created_on')[:5]
        post_obj = Post.objects.all().filter(post_status='active', visible=True).order_by('categories', '-created_on')

        image_path = 'blog/assets/img/winlinmac.jpg'

        # As per Templates Views
        first_post = featured_obj.first()
        s_post = featured_obj
        last_post = featured_obj
        context = {
            'post': post_obj,
            'f_post': featured_obj,
            'first': first_post,
            's_post': s_post,
            'last_post': last_post,
            'image_path': image_path,

        }

        return render(request, 'blog/index.html', context)

# ObjectViewedMixin
class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'blog/single_blog.html'

    def get_context_data(self, **kwargs):
        context =super().get_context_data(**kwargs)
        post_ = Post.objects.filter(slug=self.kwargs['slug'])
        post_.update(visit_count=F('visit_count') + 1)


        post_obj = get_object_or_404(Post, slug=self.kwargs['slug'])
        post_obj.visit_count = post_obj.visit_count + 1
        post_obj.save()

        related_post = Post.objects.filter(author=post_obj.author).exclude(slug=self.kwargs['slug']).order_by('-id')[:2]
        # As per templates views
        first_post = related_post.first() if related_post else ''
        last_post = related_post[1:] if related_post else ''

        context['post'] =post_obj
        context['r_post']= related_post
        context['first'] =first_post
        context['last'] =last_post
        return context

# class PostDetailView(View):

#     def get(self, request, slug, *args, **kwargs):
#         post_obj = get_object_or_404(Post, slug=slug)
#         post_obj.visit_count = post_obj.visit_count + 1
#         post_obj.save()
#         related_post = Post.objects.filter(author=post_obj.author).exclude(slug=slug).order_by('-id')[:4]

#         # As per templates views
#         first_post = related_post.first()
#         last_post = related_post[1:]

#         context = {
#             'post': post_obj,
#             'r_post': related_post,
#             'first': first_post,
#             'last': last_post
#         }
#         print("aaaaaa", context)
#         return render(request, 'blog/single_blog.html', context)


# Category View
class CategoryView(View):
    def get(self, request, slug, *args, **kwargs):
        category_obj = get_object_or_404(Category, slug=slug)
        # post = catagory_obj.blog_set.all().order_by('-id')
        post = Post.objects.filter(categories=category_obj, \
                                   post_status='active', visible=True) \
            .order_by('-created_on')
        popular = Post.objects.filter(categories=category_obj, \
                                      post_status='active', visible=True) \
            .annotate(post_count=Count('visit_count')) \
            .order_by('-visit_count')
        # as Per templates views
        featured_post = popular.first()
        popular_post = popular[1:6]
        # Pagination
        paginator = Paginator(post, 3)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context = {
            'post': page_obj,
            'pop': popular_post,
            'f_post': featured_post,
        }
        return render(request, 'blog/category.html', context)


class CategoryFunction(View):
    # @method_decorator(login_required(login_url='login'))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        catagory_obj = Category.objects.all().order_by('-id')
        context = {
            'category': catagory_obj
        }
        return render(request, 'blog/dashboard/category.html', context)

# tag View
class TagView(View):
    def get(self, request, id, *args, **kwargs):
        tag_obj = get_object_or_404(Tag, id=id)
        post = tag_obj.blog_set.all().order_by('-id')
        tag_count = post.count()
        context = {
            'tag': tag_obj,
            'post': post,
            'tag_count': tag_count
        }
        return render(request, 'home/tag.html', context)


# Subscribe Views
class SubscriptionView(View):
    def post(self, request, *args, **kwargs):

        sub_obj = request.POST.get('email')
        email = EmailSignUp.objects.filter(email=sub_obj)
        if email:
            messages.success(request, 'You are already Subscribed , Thanks!')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            subscribe = EmailSignUp.objects.create(email=sub_obj)
            subscribe.save()
            messages.success(request, 'Thanks for Subscribing')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


# search Views
class SearchView(View):
    def get(self, request, *args, **kwargs):
        search = request.GET['q']
        post = Post.objects.filter(post_status='active', visible=True)
        if len(search) > 100:
            posts = post.none()
        else:
            posts = post.filter(
                Q(title__icontains=search) |
                Q(categories__name__icontains=search) |
                Q(content__icontains=search)

            )
        context = {
            'post': posts,
            'search': search
        }
        return render(request, 'blog/search.html', context)


# Comments View
class CommentView(View):
    def post(self, request, id, *args, **kwargs):
        post = get_object_or_404(Post, id=id)
        name = request.POST.get('name')
        body = request.POST.get('body')
        comment_obj = Comment(post=post, name=name, body=body)
        comment_obj.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def test(request):
    catagory_obj = Category.objects.all()
    cat = Category.objects.all().count()
    lent = len(catagory_obj)
    # post = Catagory.blog_set.count()
    # post = Blog.objects.filter(categories__icontains = catagory_obj).count()

    # src = https://able.bio/rhett/how-to-order-by-count-of-a-foreignkey-field-in-django--26y1ug1

    post = Category.objects.all() \
        .annotate(post_count=Count('blog')) \
        .order_by('-post_count')
    context = {
        'catagory': catagory_obj,
        'cat': cat,
        'lent': lent,
        'post': post

    }
    return render(request, 'test.html', context)


"""
Author Views

"""


# user dashboard views
class Dashboard(View):
    # @method_decorator(login_required(login_url='login'))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        user = request.user
        post = user.author.blog_set.all()
        post_count = post.count()
        post_active = user.author.blog_set.filter(status='active')
        post_active_count = post_active.count()
        post_pending = user.author.blog_set.filter(status='pending')
        post_pending_count = post_pending.count()

templates/blog/author_profile.html
{% extends 'includes/base.html' %}
{% block title %} {{site_name}} | {{topics.name}} {% endblock %}

{% block custom_css %}
.p_image{
width:100%;
height:auto;
border-radius:20px;
}
.btn a{
color:white;
}
.main_wrapper{
height:100vh;
}
{% endblock %}
{% block body%}


<div class="col">
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div class="alert alert-primary" {% if message.tags %}
             class="{{ message.tags }}" {% endif %}>{{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
<div class="row main_wrapper">
    <div class="col-6 col-md-4">
        {% if author.author_image %}
        <img class="rounded-circle" width="304" height="236" src="{{ author.author_image.url }}" alt="">
        {% else %}
        <img class="p_image" src="https://genslerzudansdentistry.com/wp-content/uploads/2015/11/anonymous-user.png"
             alt="">
        {% endif %}
    </div>
    <div class="col-12 col-md-8">
        <a href="{% url 'blog:author-edit' author.id %}">
            <button class="btn btn-dark float-center btn-sm" >
            <i class="far fa-edit" style="color:green"></i>
                Edit profile
            </button>

        </a>
        <h5><strong>Username</strong></h5> {{ author.user.username }}
        <h5><strong>Name</strong></h5> {{ author.user.first_name }} {{ author.user.last_name }}
        <h5><strong>Email</strong></h5> {{ author.user.email }}
        <h5><strong>Title</strong></h5> {{ author.title }}
        <h5><strong>Profile</strong></h5>
        {{ author.profile }}

    </div>

</div>

{% endblock %}

templates/blog/image_confirm_delete.html
{% extends 'includes/base.html' %}
{% block title %} {{site_name}} | {{category.name}} {% endblock %}
{% load crispy_forms_tags %}
{% block body %}

{% if user.is_authenticated %}
<form method="post">{% csrf_token %}
  <div class="container">
<p>Are you sure you want to delete "{{ object }}"?</p>
  <button class="btn btn-danger" type="submit" value="Confirm">Confirm</button>
  </div>
</form>
{% else %}
<form>
    <div class="container">
        <div class="form-group">
            <div class="row">
                <h3> Sorry , you are not Authorized!</h3>
            </div>
        </div>
    </div>
</form>
{% endif %}
{% endblock %}

templates/blog/image_list.html
{% extends 'includes/base.html' %}
{% block title %} {{site_name}}  | {{category.name}} {% endblock %}
{% load crispy_forms_tags %}
{% block body %}

{% if user.is_authenticated %}

<form>
    <div class="container">
        <ul>
            <!-- Iterate over object_list -->
            {% for object in object_list %}

            <div class="row">
                <div class="col-6">
                    <p>{{object.name}}: ({{object.image}})</p>
                </div>
                <div class="col-6">
                    <img src="{{object.image.url}}" alt="Smiley face" width="120" height="120">
                    <button type="button" class="btn btn-secondary">
                    <a href="{% url 'blog:image-update' object.id %}" class="button">Replace</a>
                    </button>
                    <button type="button" class="btn btn-danger">
                        <a href="{% url 'blog:image-delete' object.id %}" class="button">Delete</a>
                    </button>
                </div>
            </div>
                <hr/>
                <!-- If object_list is empty -->
                {% empty %}
                <li>No objects yet.</li>
                {% endfor %}
        </ul>
    </div>
</form>
{% else %}
<form>
    <div class="container">
        <div class="form-group">
            <div class="row">
                <h3> Sorry , you are not Authorized!</h3>
            </div>
        </div>
    </div>
</form>
{% endif %}
{% endblock %}

templates/blog/search.html
{% extends 'includes/base.html' %}

{% block title %} {{site_name}}  | Search Result  {% endblock %}
{% block body %}
<div class="container pt-4 pb-4 " style="margin-bottom: 70px;">
    {% if post %}
    <h3> Showing Result of : <b>{{ search }}</b></h3>
    <br>
<div class="row">
    
{% for p in post %}

    <div class="col-lg-3">

<div class="card border-0 mb-4 box-shadow h-xl-300" style=" box-shadow: 1px 2px 5px 6px #ececec; padding: 10px;">

    <div class="card-body px-0 pb-0 d-flex flex-column align-items-start">
        <h2 class="h4 font-weight-bold">
        <a class="text-dark" href="{% url 'blog:single-post' p.slug %}"> {{ p.title}} </a>
        </h2>
        <p class="card-text">
            {{p.content|striptags|truncatechars:100}}
        </p>
        <div>
            <small class="d-block">
                <a class="" href="{% url 'blog:author-profile' p.author.id %} ">{{p.author.user.username}}</a> in <a class="" href="{% url 'blog:post-category' p.categories.slug %} ">{{ p.categories}}</a></small>
            <small class="text-muted">{{ p.created_on | timesince }} ago .  {{p.visit_count}} views</small>
        </div>
    </div>
</div>
</div>
{% endfor %}
</div>

{% else %}
<div class="col-lg-10 " style="margin:0 auto;">
 <h3>Your search - <b>{{ search }}</b> - did not match any documents.</h3> 

<h5> Suggestions: </h5>
<ul>
<li>  Make sure that all words are spelled correctly.</li>
<li>  Try different keywords.</li>
<li>  Try more general keywords.</li>
<li>  Try fewer keywords.</li>
</ul>

</div>
{% endif %}
</div>
{% endblock %}

templates/blog/sidebar.html
{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }
            .head_text{
    color: #B51D17;
  }
       
</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4 head_text">
        <h5 class="card-header head_text">Best Humidifier</h5>
    <div class="card-body">
        <p class="card-text"> This awesome blog is made on the top of our Favourite full stack Framework 'Django', follow up the tutorial to learn how we made it..!</p>
        <a href="#"
           class="btn btn-danger">Buy Now!</a>
    </div>
</div>
</div>

{% endblock sidebar %}

templates/blog/single_blog.html
{% extends 'includes/base.html' %}
{% load static %}
{% block title %} {{site_name}}  | {{post.title }} {% endblock %}
{% block body %}
<div class="container">
    <div class="jumbotron jumbotron-fluid mb-3 pl-0 pt-0 pb-0 bg-white position-relative">
        <div class="h-100 tofront">
            <div class="row justify-content-between">
                <div class="col-md-6 pt-6 pb-6 pr-6 align-self-center">


                    {% if messages %}
                    <div class="messages">
                        {% for message in messages %}
                        <div class="alert alert-primary" {% if message.tags %}
                             class="{{ message.tags }}" {% endif %}>{{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>

                        {% endfor %}
                    </div>
                    {% endif %}

                    <p class="text-uppercase font-weight-bold">
                        <a class="text-danger" href="{% url 'blog:post-category' post.categories.slug %}">{{ post.categories }}</a>

                    </p>
                    <h1 class="display-4 secondfont mb-3 font-weight-bold">{{ post.title }}</h1>
                    <div class="d-flex align-items-center">

                        {% if post.author.author_image %}
                        <img height="20" class="rounded-circle shadow" style="border-radius: 50%;"
                             src="{{ post.author.author_image.url }}">
                        {% else %}
                        <img class="rounded-circle shadow" height="70"
                             src="https://www.pngarts.com/files/11/Avatar-PNG-Transparent-Image.png" alt="">
                        {% endif %}
                        {% if post.author.id %}
                        <a class="text-muted" href="{% url 'blog:author-profile' post.author.id %}">
                            {{post.author.user.username }} ({{post.author.title}})
                        </a>
                        {% else %}
                        <a class="text-muted" href="{% url 'blog:author-profile' 0 %}">{{ post.author.user.username }}
                            ({{post.author.title}})</a>
                        {% endif %}
                    </div>
                    <small class="text-muted">
                        {{post.created_on | timesince }} ago ; {{post.visit_count }} views
                    </small>

                </div>

                <div class="col-md-6 pr-0">
                    <img src="{{post.image_url }}">
                </div>
            </div>
        </div>
    </div>
</div>


<div class="container pt-4 pb-4">
    <div class="row justify-content-center">
        <div class="col-lg-2 pr-4 mb-4 col-md-12">
            <div class="sticky-top text-center">
                <div class="text-muted">
                    Share this
                </div>
                <div class="share d-inline-block">
                    <!-- AddToAny BEGIN -->
                    <div class="a2a_kit a2a_kit_size_32 a2a_default_style">
                        <a class="a2a_dd" href="https://www.addtoany.com/share"></a>
                        <a class="a2a_button_facebook"></a>
                        <a class="a2a_button_twitter"></a>
                    </div>
                    <script async src="https://static.addtoany.com/menu/page.js"></script>
                    <!-- AddToAny END -->
                </div>
            </div>
        </div>
        <div class="col-md-12 col-lg-8">
            <article class="article-post">
                <p class="card-text ">{{ post.content | safe }}</p>
            </article>
            <div class="border p-5 bg-lightblue">
                <div class="row justify-content-between">
                    <div class="col-md-5 mb-2 mb-md-0">
                        <h5 class="font-weight-bold secondfont">Become a member</h5>
                        Get the latest news right in your inbox. We never spam!
                    </div>
                    <div class="col-md-7">
                        <form action="{% url 'blog:member-subscription' %}" method="POST">
                            <div class="row">

                                {% csrf_token %}
                                <div class="col-md-12">
                                    <input type="email" name='email' class="form-control"
                                           placeholder="Enter your e-mail address" required>
                                </div>
                                <div class="col-md-12 mt-2">
                                    <button type="submit" class="btn btn-success btn-block">Subscribe</button>
                                </div>

                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <form style="margin-top:50px;" action="{% url 'blog:comment' post.id  %}" method="POST">
                {% csrf_token %}
                <div class="row form-group">
                    <div class="col">
                        <input type="text" name='name' class="form-control" placeholder="Your Name">
                    </div>
                </div>
                <div class="form-group">
                    <textarea class="form-control" name='body' id="exampleFormControlTextarea1" rows="4"></textarea>
                </div>
                <button type="submit" class="btn btn-primary btn-round">Submit Comment</button>
            </form>
            <br>


            {% for p in post.comments.all reversed %}
            {% if forloop.counter|divisibleby:2 %}
            <div style="border-radius: 10px; margin: 5px; padding: 25px; background-color: #d8d8d8; ">
                <p><strong>{{ p.name }}</strong> at {{ p.created_at }}</p>
                <p style="padding: 20px; background-color: #f1f1f1; border-radius: 7px; border:0.5px solid #c5c5c5">{{
                    p.body }}</p>
            </div>
            {% else %}
            <div style="border-radius: 10px; margin: 5px; padding: 25px; background-color: #b3d3c0;">
                <p><strong>{{ p.name }}</strong> at {{ p.created_at }}</p>
                <p style="padding: 20px; background-color: #c5e6d3; border-radius: 7px; border:0.5px solid #c5c5c5">{{
                    p.body }}</p>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>


<div class="container pt-4 pb-4">
    <h5 class="font-weight-bold spanborder"><span>Read next</span></h5>

    <div class="row">

        <div class="col-lg-6">

            <div class="card border-0 mb-4 box-shadow h-xl-300">
                <div style="background-image: url({% static 'blog/assets/img/demo/3.jpg' %}); ">
                    <img src="{{ first.image_url }}"
                         style="height: 200px; background-size: cover; background-repeat: no-repeat; width: 100%;"
                         alt="">
                </div>
                <div class="card-body px-0 pb-0 d-flex flex-column align-items-start">
                    <h2 class="h4 font-weight-bold">
                        {% if first.slug %}
                        <a class="text-dark" href="{% url 'blog:single-post' first.slug %}"> {{ first.title}} </a>
                        {% else %}
                        <a class="text-dark" href="{% url 'blog:single-post'  0 %}"> {{ first.title}} </a>
                        {% endif %}
                    </h2>
                    <p class="mb-3">
                          {{first.content |truncatechars:150 |striptags}}
                         <a href="{% url 'blog:single-post' first.slug %}" class="btn-green">Read More</a>
                         {% comment %} <a href="{% url 'single-post' slug=post.slug %}" class="btn-green">>Read More</a> {% endcomment %}

                    </p>
                    <div>
                        <small class="d-block">
                            {% if first.author.author_image %}
                            <img height="20" class="rounded-circle shadow" style="border-radius: 50%;"
                                 src="{{ first.author.author_image.url }}">
                            {% else %}
                            <img class="rounded-circle shadow" height="20"
                                 src="https://www.pngarts.com/files/11/Avatar-PNG-Transparent-Image.png" alt="">
                            {% endif %}
                            {% if first.author.id %}
                            <a class="text-muted" href="{% url 'blog:author-profile' first.author.id %}">{{first.author.user.username}}</a>
                            {% else %}
                            <a class="text-muted" href="{% url 'blog:author-profile' 0 %}">{{first.author.user.username}}</a>
                            {% endif %}
                        </small>
                        <small class="text-muted">{{ first.created_on | timesince }} ago . {{first.visit_count}}
                            views</small>
                    </div>
                </div>
            </div>

        </div>

        <div class="col-lg-6">

            <div class="flex-md-row mb-4 box-shadow h-xl-300">
                {% for p in last %}
                <div class="mb-3 d-flex align-items-center">
                    <img height="80" src="{{p.image_url}}">
                    <div class="pl-3">
                        <h2 class="mb-2 h6 font-weight-bold">

                            {% if p.slug %}
                            <a class="text-dark" href="{% url 'blog:single-post' p.slug %}">{{p.title}}</a>
                            {% else %}
                            <a class="text-dark" href="{% url 'blog:single-post'  0 %}"> {{ first.title}} </a>

                            {% endif %}
                        </h2>
                        <div class="card-text text-muted small">
                            {% if p.author.author_image %}
                            <img class="rounded-circle shadow" height="20" style="border-radius: 50%;"
                                 src="{{ p.author.author_image.url }}">
                            {% else %}
                            <img class="rounded-circle shadow" height="20"
                                 src="https://www.pngarts.com/files/11/Avatar-PNG-Transparent-Image.png" alt="">
                            {% endif %}
                            {% if post.author.id %}
                            <a class="text-muted" href="{% url 'blog:author-profile' p.author.id %}">
                                {{ p.author.user.username }}</a> in
                            <a class="text-dark" href="{% url 'blog:post-category' p.slug %}">
                                {{p.categories }}
                            </a>
                            {% else %}
                            <a class="text-muted" href="{% url 'blog:author-profile' 0 %}">{{ p.author.user.username
                                }}</a> in <a class="text-dark" href="{% url 'blog:post-category' p.slug %}">{{p.categories
                            }} </a>
                            {% endif %}
                        </div>
                        <small class="text-muted">{{ p.created_on | timesince }} ago . {{p.visit_count}} views</small>
                    </div>
                </div>
                {% endfor %}
            </div>


        </div>


    </div>

</div>


{% endblock %}