app/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView
from django.urls import re_path
from .views import AboutView, contacts, policy, frequentlyaskedquestions

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('django.contrib.auth.urls')),
    path('authentication/', include('authentication.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', TemplateView.as_view(template_name='authenticate/profile.html'), name='user_profile'),
    path('about/', AboutView, name='about'),
    path('contact/', contacts, name='contacts'),
    path('frequently-asked-questions/', frequentlyaskedquestions, name='frequentlyaskedquestions'),
    path('policy/', policy, name='privacy-policy'),

    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name="account/password_reset.html"),
         name="reset_password"),
    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"),
         name="password_reset_done"),
    path('', include('blog.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import (
    # UserLoginCreateView, 
    # UserRegistrationCreateView,
    # logout_view,
    # ClientRegistrationCreateView,
    show_notification,
    delete_notification,
    profile_view,
    ProfileUpdateView,
    TimezoneUpdateView
)

app_name = 'authentication'

urlpatterns = [
    # path('login', UserLoginCreateView.as_view(), name='login'),
    # path('logout/', logout_view, name='logout'),
    # path('signup/', UserRegistrationCreateView.as_view(), name='sign_up'),
    # path('signup_client/', ClientRegistrationCreateView.as_view(), name='cient_sign_up'),
    path('notification/<int:notification_id>/',show_notification,name='show_notifications'),
    path('notification/delete/<int:notification_id>/',delete_notification,name='delete_notification'),
    path('profile/',profile_view,name='profile'),
    path('<pk>/update', ProfileUpdateView.as_view(), name='profile-update'),
    path('<pk>/timezone/update', TimezoneUpdateView.as_view(), name='timezone-update'),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="account/password_reset.html"),name="reset_password"), 
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"),name="password_reset_done"),

]

templates/authenticate/login.html
{% comment %} {% extends 'includes/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}
<div class="container">
    <div class="row justify-content-center h-100">
        <div class="col-xl-6">
            <div class="form-input-content">
                <div class="card login-form mb-0">
                    <div class="card-body pt-5">
                        <a class="text-center"><h4>Login Now!</h4></a>
                        {%if messages%}
                        <div class="alert alert-danger">
                            {% for message in messages %} {% if forloop.first %}
                            {{message}} {% endif %} {% endfor %}
                        </div>
                        {%endif%}
                        <form class="" method="POST">
                            {% csrf_token %}
                            {{ form |crispy }}
                            <input type="submit" value="Login" class="btn btn-danger w-100">
                        </form>
                        <div class="row">
                            <div class="col col-md-6">
                                <p class="mt-5 login-form__footer" style="color:black;">
                                    No account?
                                    <a
                                            href="{% url 'authentication:sign_up' %}"
                                            class="text-primary"
                                    >Sign Up</a
                                    >
                                    Now!!
                                </p>

                                <p class="mt-5 login-form__footer" style="color:black;">
                                    Forgot Password?
                                    <a href="{% url 'reset_password' %}" class="text-primary">Reset!</a>
                                </p>

                            </div>
                            <div class="col col-md-6">
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock%} {% endcomment %}

templates/authenticate/profile.html
{% extends 'includes/base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}

<div class="content my-5">
    <hr>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h3 style="color:#b51d17;">My Profile</h3>
<!--                <button data-toggle="modal" data-target="#bioModal" data-id="{{ request.user.id }}"-->
<!--                        type="button" class="btn btn-warning margin-bottom">-->
<!--                    Edit Bio-->
<!--                </button>-->
                <button  type="button" class="btn btn-warning margin-bottom">
                   <a href="{% url 'authentication:profile-update' request.user.id %}">Edit Bio</a>
                </button>

            </div>
            <div class="card-body">
                <table class="table table-striped table-hover table-bordered">

                    <tbody>
                    <tr>
                        <th scope="row">Country</th>
                        <td colspan="2">{{request.user.country}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Name</th>
                        <td colspan="2">{{request.user.first_name}}  {{request.user.last_name}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Username</th>
                        <td colspan="2">{{request.user.username}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Email</th>
                        <td colspan="2" id="useremail">{{request.user.email}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Password</th>
                        <td>
                            .......
                            <button data-toggle="modal"  data-id="{{ request.user.id }}"
                                    type="button" class="btn btn-danger margin-bottom">
                                <a href="{% url 'reset_password' %}">Reset Password!</a>
                            </button>



                        </td>
                    </tr>
                    <tr>
                        <th scope="row">City</th>
                        <td colspan="2">{{request.user.city}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Address</th>
                        <td colspan="2">{{request.user.address}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Zip Code</th>
                        <td colspan="2">{{request.user.zip_code}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Timezone</th>
                        <td colspan="2">{{request.user.time_zone}}
                            <button type="button" class="btn btn-secondary btn-sm pull-right building-link">
                                <a href="{% url 'authentication:timezone-update' request.user.id %}">Update Timezone</a>

                            </button>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!--  start update modal -->
    <div class="modal fade bd-bio-modal-lg" tabindex="-1" role="dialog" id="bioModal"
         aria-labelledby="myBioModalLabel" aria-hidden="false">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 style="color:#b51d17;" id="exampleModalLabel">Update your Bio ( {{ request.user.id }} )</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
    </div>

    <!--  end update modal-->

</div>
</div>
{% include 'scripts.html' %}

templates/authenticate/register.html
{% extends 'includes/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %} 
<body class="h-100">
    <div class="">
        <div class="container-fluid">
            <div class="row justify-content-center h-100">
                <div class="col-xl-6">
                    <div class="form-input-content">
                        <div class="card login-form mb-0">
                            <div class="card-body pt-5">
                                <a class="text-center" > <h4>BlogTemplate Signup</h4></a>
                                <form class="mt-5 mb-5 login-input" method="POST">
                                    {% csrf_token %}
                                    {{form|crispy}}
                                    <button class="btn btn-danger w-100">Sign Up</button>
                                </form>
                                    <p class="mt-5 login-form__footer" style="color:black;">Already have an account? <a href="{% url 'authentication:login' %}" class="text-primary">Sign In </a> now</p>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</body>
{% endblock body%}

templates/authenticate/update_profile.html
{% include 'links.html' %}
{% include 'includes/header.html' %}
{% load crispy_forms_tags %}
{% load humanize %}

<div class="content my-5">
    <hr>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h3 style="color:#b51d17;">Update Bio</h3>
            </div>
            <div class="card-body">
                <form class="mt-5 mb-5 login-input" method="POST" style="color:blue;">
                                    {% csrf_token %}

                      <div class="row">
                          <div class="col-6">
                            {{ form.first_name|as_crispy_field }}
                          </div>
                          <div class="col-6">
                            {{ form.last_name|as_crispy_field }}
                          </div>
                      </div>
                    <div class="row">
                        {{ form.email|as_crispy_field }}
                    </div>
                    <div class="row">
                          <div class="col-6">
                            {{ form.time_zone|as_crispy_field }}
                          </div>
                          <div class="col-6">
                            {{ form.country|as_crispy_field }}
                          </div>
                      </div>
                     <div class="row">
                          <div class="col-4">
                            {{ form.phone|as_crispy_field }}
                          </div>
                          <div class="col-4">
                            {{ form.additional_phone |as_crispy_field }}
                          </div>
                         <div class="col-4">
                            {{ form.night_calls |as_crispy_field }}
                          </div>
                      </div>
                    <div class="row">
                          <div class="col-4">
                            {{ form.city|as_crispy_field }}
                          </div>
                          <div class="col-4">
                            {{ form.address |as_crispy_field }}
                          </div>
                         <div class="col-4">
                            {{ form.zip_code |as_crispy_field }}
                          </div>
                      </div>

                     <div class="row" style="padding-top:10px;">
                        <div class="col-8">
                        </div>
                        <div class="col-4">
                            <div class="row">
                                <div class="col-2">
                                </div>
                                <div class="col-2">
                                <button type="button" class="btn btn-secondary pull-right">
                                <a href="{% url 'authentication:profile' %}">Close</a>
                                </button>
                                    </div>
                                <div class="col-2">
                                </div>
                                <div class="col-6">
                        <button class="btn btn-primary w-100 pull-right">Update</button>
                                </div>
                                </div>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>

</div>

templates/authenticate/update_timezone_profile.html
{% include 'links.html' %}
{% include 'includes/header.html' %}
{% load crispy_forms_tags %}
{% load humanize %}

<div class="content my-5">
    <hr>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h3 style="color:#b51d17;">Update Timezone</h3>
            </div>
            <div class="card-body">
                <form class="mt-5 mb-5 login-input" method="POST" style="color:blue;">
                                    {% csrf_token %}

                    <div class="row">
                          <div class="col-6">
                            {{ form.time_zone|as_crispy_field }}
                          </div>
                          <div class="col-6">
                            {{ form.country|as_crispy_field }}
                          </div>
                      </div>

                    <div class="row" style="padding-top:10px;">
                        <div class="col-8">
                        </div>
                        <div class="col-4">
                            <div class="row">
                                <div class="col-2">
                                </div>
                                <div class="col-2">
                                <button type="button" class="btn btn-secondary pull-right">
                                <a href="{% url 'authentication:profile' %}">Close</a>
                                </button>
                                    </div>
                                <div class="col-2">
                                </div>
                                <div class="col-6">
                        <button class="btn btn-primary w-100 pull-right">Update</button>
                                </div>
                                </div>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>

</div>